# Generated by Django 6.0.6 on 2026-06-17 17:42

import datetime

import django.db.models.deletion
from django.db import migrations, models

import scanner.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("st_dev", models.BigIntegerField()),
                ("st_ino", models.BigIntegerField()),
                ("size", models.BigIntegerField()),
                ("nlink", models.PositiveIntegerField()),
                (
                    "links_found",
                    models.PositiveIntegerField(
                        help_text="Number of hard links found during the scan. May be > nlink if "
                        "some links are outside of the scanned tree."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reclaimable", "Reclaimable"),
                            ("seeding_hold", "Seeding Hold"),
                            ("in_library", "In Library"),
                            ("in_progress", "In Progress"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("media", "Media"), ("sidecar", "Sidecar"), ("other", "Other")],
                        max_length=16,
                    ),
                ),
                (
                    "trees",
                    models.JSONField(
                        default=list,
                        help_text="Subset of Tree values this blob is reachable through",
                    ),
                ),
                (
                    "torrent_tracked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this blob is part of a torrent in qBittorrent",
                    ),
                ),
                (
                    "seeding_met",
                    models.BooleanField(
                        help_text="Whether seeding requirements for the associated torrent are "
                        "met. ANDed across owning torrents (if multiple, eg cross-seed). "
                        "null when untracked.",
                        null=True,
                    ),
                ),
                (
                    "latest_seeding_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Latest completed_on (which is when seeding stats) for any "
                        "torrent of this file",
                        null=True,
                    ),
                ),
                ("seeding_end", models.DateTimeField(blank=True, null=True)),
                ("orphan_reason", models.CharField(blank=True, default="", max_length=64)),
                ("cross_seed", models.BooleanField(default=False)),
                ("multi_link", models.BooleanField(default=False)),
                ("partial_torrent", models.BooleanField(default=False)),
                ("seedable_idle", models.BooleanField(default=False)),
                ("links_outside_scope", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "library_roots",
                    models.JSONField(
                        default=scanner.models.default_library_roots,
                        help_text="List of paths to library root directories (eg movies, tv)",
                    ),
                ),
                (
                    "torrent_roots",
                    models.JSONField(
                        default=scanner.models.default_torrent_roots,
                        help_text="List of paths to torrent root directories",
                    ),
                ),
                (
                    "seeding_min_days",
                    models.PositiveIntegerField(
                        default=14, help_text="Minimum number of seeding days"
                    ),
                ),
                (
                    "seeding_min_ratio",
                    models.FloatField(default=1.0, help_text="Minimum seeding ratio"),
                ),
                (
                    "quarantine_window",
                    models.DurationField(
                        default=datetime.timedelta(seconds=1800),
                        help_text="Quarantine window wherein a newly created or modified link "
                        "cannot be modified",
                    ),
                ),
            ],
            options={
                "verbose_name": "config",
                "verbose_name_plural": "config",
            },
        ),
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        help_text="Lifecycle status of the scan",
                        max_length=16,
                    ),
                ),
                ("as_of", models.DateTimeField(help_text="When the scan began")),
                (
                    "seeding_min_days",
                    models.PositiveIntegerField(
                        help_text="Minimum seeding days, copied from Config at scan start"
                    ),
                ),
                (
                    "seeding_min_ratio",
                    models.FloatField(
                        help_text="Minimum seeding ratio, copied from Config at scan start"
                    ),
                ),
                (
                    "quarantine_window",
                    models.DurationField(
                        help_text="Quarantine window, copied from Config at scan start"
                    ),
                ),
                (
                    "qbittorrent_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="qBittorrent application version observed during the scan",
                        max_length=32,
                    ),
                ),
                (
                    "summary_totals",
                    models.JSONField(
                        default=dict,
                        help_text="Computed totals: reclaimable totals plus per-status breakdown",
                    ),
                ),
            ],
            options={
                "ordering": ["-as_of"],
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.TextField(help_text="Share-relative path")),
                ("name", models.TextField(help_text="Basename of the path")),
                (
                    "kind",
                    models.CharField(
                        choices=[("media", "Media"), ("sidecar", "Sidecar"), ("other", "Other")],
                        max_length=16,
                    ),
                ),
                (
                    "tree",
                    models.CharField(
                        choices=[
                            ("library", "Library"),
                            ("torrents", "Torrents"),
                            ("loose", "Loose"),
                        ],
                        max_length=16,
                    ),
                ),
                ("mtime", models.DateTimeField()),
                (
                    "blob",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="scanner.blob",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="scanner.scan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="blob",
            name="scan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="blobs", to="scanner.scan"
            ),
        ),
        migrations.CreateModel(
            name="Torrent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hash", models.CharField(max_length=40)),
                ("state", models.CharField(max_length=32)),
                ("ratio", models.FloatField()),
                (
                    "completed_on",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the torrent completed downloading and seeding started",
                        null=True,
                    ),
                ),
                ("seeding_time", models.DurationField(blank=True, null=True)),
                ("content_path", models.TextField()),
                ("save_path", models.TextField()),
                ("seeding_met", models.BooleanField(default=False)),
                ("seeding_end", models.DateTimeField(blank=True, null=True)),
                ("partial_torrent", models.BooleanField(default=False)),
                ("reclaim_if_removed_bytes", models.BigIntegerField(default=0)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="torrents",
                        to="scanner.scan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlobTorrent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file_index", models.IntegerField()),
                (
                    "blob",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blob_torrents",
                        to="scanner.blob",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blob_torrents",
                        to="scanner.scan",
                    ),
                ),
                (
                    "torrent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blob_torrents",
                        to="scanner.torrent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="blob",
            name="torrents",
            field=models.ManyToManyField(
                related_name="blobs", through="scanner.BlobTorrent", to="scanner.torrent"
            ),
        ),
        migrations.AddIndex(
            model_name="blob",
            index=models.Index(fields=["scan", "status"], name="scanner_blo_scan_id_1b72ce_idx"),
        ),
        migrations.AddConstraint(
            model_name="blob",
            constraint=models.UniqueConstraint(
                fields=("scan", "st_dev", "st_ino"), name="uniq_blob_per_scan_inode"
            ),
        ),
    ]
