# Generated by Django 6.0.6 on 2026-06-16 15:42

import datetime

from django.db import migrations, models

import scanner.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("library_roots", models.JSONField(default=scanner.models.default_library_roots)),
                ("torrent_roots", models.JSONField(default=scanner.models.default_torrent_roots)),
                ("seeding_min_days", models.PositiveIntegerField(default=14)),
                ("seeding_min_ratio", models.FloatField(default=1.0)),
                (
                    "quarantine_window",
                    models.DurationField(default=datetime.timedelta(seconds=1800)),
                ),
            ],
            options={
                "verbose_name": "config",
                "verbose_name_plural": "config",
            },
        ),
    ]
