# Generated by Django 6.0.6 on 2026-06-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blob",
            name="cross_seed",
            field=models.BooleanField(
                default=False, help_text="Blob served by more than one torrent"
            ),
        ),
        migrations.AlterField(
            model_name="blob",
            name="links_outside_scope",
            field=models.BooleanField(
                default=False,
                help_text="Link count could not be accounted for by only files under the scan root",
            ),
        ),
        migrations.AlterField(
            model_name="blob",
            name="multi_link",
            field=models.BooleanField(
                default=False, help_text="Multiple hard links in the same tree"
            ),
        ),
        migrations.AlterField(
            model_name="blob",
            name="orphan_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Reason that a non-media file couldn't be linked to a media file and is "
                "safe for deletion",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="blob",
            name="partial_torrent",
            field=models.BooleanField(
                default=False,
                help_text="A torrent linked to this blob has blobs that do not all share "
                "the same status",
            ),
        ),
        migrations.AlterField(
            model_name="blob",
            name="seedable_idle",
            field=models.BooleanField(
                default=False,
                help_text="In the library and torrent trees, but isn't seeding. "
                "Covers the case of no owning torrent or an owning torrent that is stopped. "
                "Not set when the only owning torrents are in an error or other state.",
            ),
        ),
        migrations.AlterField(
            model_name="blob",
            name="seeding_end",
            field=models.DateTimeField(
                blank=True,
                help_text="When seeding requirements of the associated torrent will be met if "
                "seeding_met is false",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="torrent",
            name="partial_torrent",
            field=models.BooleanField(
                default=False, help_text="Blobs in this torrent do not all share the same status"
            ),
        ),
        migrations.AlterField(
            model_name="torrent",
            name="seeding_end",
            field=models.DateTimeField(
                blank=True,
                help_text="When seeding requirements will be met if seeding_met is false",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="torrent",
            name="seeding_met",
            field=models.BooleanField(
                default=False, help_text="Whether seeding requirements have been met"
            ),
        ),
        migrations.AlterField(
            model_name="torrent",
            name="seeding_time",
            field=models.DurationField(
                blank=True,
                help_text="How long since the torrent started seeding (does not account for if the "
                "torrent was stopped)",
                null=True,
            ),
        ),
    ]
