# Generated by Django 6.0.6 on 2026-06-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0002_add_help_texts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blob",
            name="status",
            field=models.CharField(
                choices=[
                    ("reclaimable", "Reclaimable"),
                    ("linked_externally", "Linked Externally"),
                    ("seeding_hold", "Seeding Hold"),
                    ("in_library", "In Library"),
                    ("in_progress", "In Progress"),
                ],
                max_length=20,
            ),
        ),
    ]
