# Generated by Django 6.0.6 on 2026-06-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0003_alter_blob_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scan",
            name="summary_totals",
        ),
        migrations.AddField(
            model_name="scan",
            name="status_totals",
            field=models.JSONField(
                default=dict,
                help_text="Per-status count and byte totals, keyed by Blob.Status value",
            ),
        ),
    ]
