# Generated by Django 6.0.6 on 2026-07-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0004_remove_scan_summary_totals_scan_status_totals"),
    ]

    operations = [
        migrations.AddField(
            model_name="torrent",
            name="added_on",
            field=models.DateTimeField(
                blank=True, help_text="When the torrent was added to the client", null=True
            ),
        ),
        migrations.AddField(
            model_name="torrent",
            name="category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Torrent category in the torrent client",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="torrent",
            name="last_activity",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time the torrent had upload/download activity",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="torrent",
            name="name",
            field=models.TextField(
                default="", help_text="Torrent name as reported by the torrent client"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="torrent",
            name="private",
            field=models.BooleanField(
                default=False, help_text="Whether the torrent is from a private tracker"
            ),
        ),
        migrations.AddField(
            model_name="torrent",
            name="size",
            field=models.BigIntegerField(
                default=0, help_text="Total size in bytes of the torrent's selected files"
            ),
        ),
        migrations.AddField(
            model_name="torrent",
            name="tracker",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Currently-working tracker URL reported by the client",
            ),
        ),
    ]
