# Generated by Django 6.0.6 on 2026-07-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0005_torrent_added_on_torrent_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blob",
            old_name="seedable_idle",
            new_name="could_seed",
        ),
        migrations.RemoveField(
            model_name="blob",
            name="partial_torrent",
        ),
        migrations.RemoveField(
            model_name="torrent",
            name="partial_torrent",
        ),
        migrations.AddField(
            model_name="torrent",
            name="raw_state",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Raw state as reported by the torrent client",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="torrent",
            name="reclaim_state",
            field=models.CharField(
                choices=[("full", "Full"), ("partial", "Partial"), ("none", "None")],
                default="none",
                help_text="Reclaim status of the torrent's owned blobs: full (all reclaimable), "
                "partial (a mix of reclaimable and non-reclaimable), "
                "or none (no reclaimable blob)",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="blob",
            name="torrent_tracked",
            field=models.BooleanField(
                default=False,
                help_text="Whether this blob is part of a torrent in the torrent client",
            ),
        ),
        migrations.AlterField(
            model_name="torrent",
            name="state",
            field=models.CharField(
                choices=[
                    ("seeding", "Seeding"),
                    ("downloading", "Downloading"),
                    ("checking", "Checking"),
                    ("moving", "Moving"),
                    ("queued", "Queued"),
                    ("error", "Error"),
                    ("stopped", "Stopped"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
    ]
