# Generated by Django 6.0.6 on 2026-07-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0006_remove_blob_partial_torrent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="torrent",
            name="uploaded",
            field=models.BigIntegerField(default=0, help_text="Amount of data uploaded in bytes"),
        ),
    ]
