# Generated by Django 6.0.6 on 2026-09-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0007_torrent_uploaded"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="finished_at",
            field=models.DateTimeField(blank=True, help_text="When the scan completed", null=True),
        ),
    ]
