# Generated by Django 6.0.6 on 2026-09-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0008_scan_finished_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="free_bytes",
            field=models.BigIntegerField(
                default=0,
                help_text="Bytes available on the share filesystem at scan time",
            ),
        ),
    ]
